# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('text', models.TextField()),
                ('username', models.TextField()),
                ('display_name', models.TextField()),
                ('retweet_count', models.IntegerField()),
                ('profile_image_url', models.URLField()),
                ('in_reply_to_status_id', models.ManyToManyField(null=True, related_name='_tweet_in_reply_to_status_id_+', to='conversation.Tweet')),
            ],
        ),
    ]
