# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0003_auto_20160309_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='display_name',
            field=models.CharField(max_length=30),
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='in_reply_to_status_id',
        ),
        migrations.AddField(
            model_name='tweet',
            name='in_reply_to_status_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='conversation.Tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
