# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0005_tweet_favourites_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='favourites_count',
            field=models.IntegerField(),
        ),
    ]
