# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0007_auto_20160309_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='in_reply_to_status_id',
        ),
        migrations.AddField(
            model_name='tweet',
            name='in_reply_to_status_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='_tweet_in_reply_to_status_id_+', to='conversation.Tweet'),
        ),
    ]
