# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0008_auto_20160316_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_status_id',
            field=models.ManyToManyField(blank=True, related_name='_tweet_in_reply_to_status_id_+', to='conversation.Tweet'),
        ),
    ]
