# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0009_auto_20160316_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='in_reply_to_status_id',
        ),
        migrations.AddField(
            model_name='tweet',
            name='in_reply_to_status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conversation.Tweet'),
        ),
    ]
